server:
  port: 8080

app:
  checkUpdatesPeriod: 1000
  webhookEnabled: true
  webhookAddress: https://7abcdafa.ngrok.io/receiveUpdate
  token: 679996290:AAGTVQhR-lFTnx4nZ3hQKKl9uvrstm-xUOI

spring:
  application:
    name: dist-bot